[project]
name = "platform-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wenzi", email = "ytq12875@163.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "pymysql>=1.2.0",
]

[project.scripts]
platform-backend = "platform_backend:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
